const ARCHIVE_ADD = 'ARCHIVE_ADD';
const ARCHIVE_DELETE = 'ARCHIVE_DELETE';
const ARTICLES_ADD = 'ARTICLES_ADD';
const ARTICLES_CLEAR = 'ARTICLES_CLEAR';

export {ARCHIVE_ADD, ARCHIVE_DELETE, ARTICLES_ADD, ARTICLES_CLEAR};
